apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2019-07-11T21:03:25Z'
  generation: 9
  labels:
    app: postgresql-nats-dev-persistent
    app-group: tob
    template: postgresql-nats-dev-persistent-template
  name: postgresql-nats-dev
  namespace: fsxqpf-prod  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: postgresql-nats-prod
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: postgresql-nats-prod
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_USER
                  name: nats-db
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_PASSWORD
                  name: nats-db           
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_DATABASE_NAME
                  name: nats-db
          image: >-
            docker-registry.default.svc:5000/gl2uos-tools/postgresql@sha256:259e854f914b5fcb8f649c0599f41209e1020b208629492d8404551e350b8a27
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          name: postgresql-nats-dev
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d
                  $POSTGRESQL_DATABASE -c 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 4000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresql-nats-dev-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgresql-nats-dev-data
          persistentVolumeClaim:
            claimName: postgresql-nats-dev
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgresql-nats-dev
        from:
          kind: ImageStreamTag
          name: 'postgresql:dev'
          namespace: gl2uos-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/gl2uos-tools/postgresql@sha256:259e854f914b5fcb8f649c0599f41209e1020b208629492d8404551e350b8a27
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-07-18T15:28:29Z'
      lastUpdateTime: '2019-07-18T15:28:29Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-07-18T15:27:53Z'
      lastUpdateTime: '2019-07-18T15:28:30Z'
      message: replication controller "postgresql-nats-dev-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
  details:
    causes:
      - type: Manual
    message: manual change
  latestVersion: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1