apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-08-22T18:28:14Z'
  generation: 12
  labels:
    app: nats-nodec
  name: nats-nodec
  namespace: fsxqpf-prod
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    app: nats-nodec
    deploymentconfig: nats-nodec
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: nats-nodec
        deploymentconfig: nats-nodec
    spec:
      containers:
        - args:
            - '-m'
            - '8222'
            - '-store'
            - SQL
            - '-sql_driver'
            - postgres
            - '-sql_source'
            - 'postgresql://@postgresql-nats-dev:5432/nats-db?sslmode=disable'
            - '-clustered'
            - '-cluster_node_id'
            - 'nodec'            
            - '-cluster_log_path'
            - /mnt/natsdata/
            - '-cid'
            - qnet           
          env:
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_USER
                  name: nats-db
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_PASSWORD
                  name: nats-db
            - name: PG_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_DATABASE_NAME
                  name: nats-db
          image: >-
            docker-registry.default.svc:5000/gl2uos-tools/nats-streaming@sha256:44adaec0bdce272f7aadafe0869c1108c2109e244e55e295124f01bf438822b9
          imagePullPolicy: Always
          name: nats-nodec
          ports:
            - containerPort: 4222
              protocol: TCP
            - containerPort: 8222
              protocol: TCP
          resources: {}
          terminationMessagePath: /test/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt/natsdata
              name: volume-3cktx
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-3cktx
          persistentVolumeClaim:
            claimName: cluster-log-path
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - nats-nodec
        from:
          kind: ImageStreamTag
          name: 'nats-streaming:v.16'
          namespace: gl2uos-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/gl2uos-tools/nats-streaming@sha256:44adaec0bdce272f7aadafe0869c1108c2109e244e55e295124f01bf438822b9
      type: ImageChange