apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: '2019-04-18T19:34:21Z'
  generation: 20
  labels:
    app: apicurio-studio-api
    template: apicurio-studio
  name: apicurio-studio-api
  namespace: gl2uos-tools
  resourceVersion: '817060952'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/gl2uos-tools/deploymentconfigs/apicurio-studio-api
  uid: f7506a02-6210-11e9-9558-0050568379a2
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: apicurio-studio-api
    deploymentconfig: apicurio-studio-api
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apicurio-studio-api
        deploymentconfig: apicurio-studio-api
        template: apicurio-studio
    spec:
      containers:
        - env:
            - name: APICURIO_KC_AUTH_URL
              value: 'https://sso-dev.pathfinder.gov.bc.ca/auth'
            - name: APICURIO_KC_REALM
              value: sbc
            - name: APICURIO_DB_DRIVER_NAME
              value: postgresql
            - name: APICURIO_DB_CONNECTION_URL
              value: 'jdbc:postgresql://postgresql:5432/apicuriodb'
            - name: APICURIO_DB_TYPE
              value: postgresql9
            - name: APICURIO_DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: postgresql
            - name: APICURIO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: postgresql
            - name: APICURIO_MIN_HEAP
              value: 512m
            - name: APICURIO_MAX_HEAP
              value: 1400m
            - name: APICURIO_MICROCKS_API_URL
              value: 'https://mock-lear-tools.pathfinder.gov.bc.ca'
            - name: APICURIO_MICROCKS_CLIENT_ID
              value: microcks-app-js
            - name: APICURIO_MICROCKS_CLIENT_SECRET
              value: df450091-ae69-49ba-ac46-251bed67cbb5
          image: >-
            docker-registry.default.svc:5000/gl2uos-tools/apicurio-api@sha256:7b5d30a285c54b1dc70378bcb3560ca097d07e169cd63ac961d1d94366b3bbdf
          imagePullPolicy: Always
          name: apicurio-studio-api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1700Mi
            requests:
              cpu: 100m
              memory: 800Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - apicurio-studio-api
        from:
          kind: ImageStreamTag
          name: 'apicurio-api:latest'
          namespace: gl2uos-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/gl2uos-tools/apicurio-api@sha256:7b5d30a285c54b1dc70378bcb3560ca097d07e169cd63ac961d1d94366b3bbdf
      type: ImageChange
    - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-05-02T16:00:52Z'
      lastUpdateTime: '2019-05-02T16:01:11Z'
      message: replication controller "apicurio-studio-api-12" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2019-06-11T19:45:49Z'
      lastUpdateTime: '2019-06-11T19:45:49Z'
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - type: ConfigChange
    message: config change
  latestVersion: 12
  observedGeneration: 20
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1