---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-streaming-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator
  template:
    metadata:
      labels:
        name: nats-streaming-operator
    spec:      
      containers:
      - name: nats-streaming-operator
        image: docker-registry.default.svc:5000/gl2uos-tools/nats-streaming@sha256:1aa0aaee4333071b448ea9e73ed96814a0fbe674fa6992c409fe1c96707b06eb        
        imagePullPolicy: Always
        env:
        - name: hak2zo-dev
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace