apiVersion: v1
kind: Service
metadata:
  labels:
    app: nats-db
    template: NATS-Streaming
  name: nats-db
  namespace: hak2zo-prod  
spec: 
  ports:
    - name: nats-db
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: nats-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}