---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: "example-stan-db"
spec:
  natsSvc: "example-nats"
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator

  # Explicitly set that the managed NATS Streaming instance
  # will be using an SQL storage, to ensure that only a single
  # instance is available.
  store: SQL

  # In order to use DB store support, it is needed to include
  # the credentials as a secret on a mounted file.
  configFile: "/etc/stan/config/secret.conf"

  # Define Pod Spec
  template:
    spec:
      containers:
        - name: nats-streaming-operator
          image: docker-registry.default.svc:5000/gl2uos-tools/nats-streaming@sha256:1aa0aaee4333071b448ea9e73ed96814a0fbe674fa6992c409fe1c96707b06eb        
      volumes:
      - name: stan-secret
        secret:
          secretName: stan-secret
      containers:
        - name: nats-streaming
          volumeMounts:
          - mountPath: /etc/stan/config
            name: stan-secret
	    readOnly: true