apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2019-07-05T03:28:16Z'
  generation: 1
  name: nats-streaming-operator
  namespace: hak2zo-dev
  resourceVersion: '850723777'
  selfLink: /apis/apps/v1/namespaces/hak2zo-dev/deployments/nats-streaming-operator
  uid: ed98b56d-9ed4-11e9-9cfd-005056832285
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: nats-streaming-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nats-streaming-operator
    spec:
      containers:
        - env:
          - name: hak2zo-dev
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace       
          image: docker-registry.default.svc:5000/hak2zo-tools/nats-streaming@sha256:1aa0aaee4333071b448ea9e73ed96814a0fbe674fa6992c409fe1c96707b06eb 
          imagePullPolicy: Always
          name: nats-streaming-operator          
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File             
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-07-05T03:28:26Z'
      lastUpdateTime: '2019-07-05T03:28:26Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-07-05T03:28:16Z'
      lastUpdateTime: '2019-07-05T03:28:26Z'
      message: >-
        ReplicaSet "nats-streaming-operator-7c5c77b884" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1