apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-06-18T18:20:41Z'
  labels:
    app: nats-streaming
  name: nats-streaming
  namespace: fsxqpf-prod  
spec: 
  ports:
    - name: 4222-tcp
      port: 4222
      protocol: TCP
      targetPort: 4222
    - name: 8222-tcp
      port: 8222
      protocol: TCP
      targetPort: 8222
  selector:
    deploymentconfig: nats-streaming
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
