apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: 'postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}'
  creationTimestamp: '2019-07-11T21:03:54Z'
  labels:
    app: postgresql-nats-dev-persistent
    app-group: tob
    template: postgresql-nats-dev-persistent-template
  name: postgresql-nats-dev
  namespace: hak2zo-dev
  resourceVersion: '860300800'
  selfLink: /api/v1/namespaces/hak2zo-dev/services/postgresql-nats-dev
  uid: 644b7144-a41f-11e9-9fe2-0050568348cc
spec:
  clusterIP: 172.50.147.184
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgresql-nats-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}